# Generated by Django 4.1.4 on 2023-01-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['email', 'password'], name='email_password_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['last_name', 'first_name'], name='last_name_first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='authuser',
            index=models.Index(fields=['first_name'], name='first_name_idx'),
        ),
        migrations.AlterModelTable(
            name='authuser',
            table='users',
        ),
    ]
