# Generated by Django 4.1.4 on 2023-01-02 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('account_type', models.CharField(max_length=15, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_accounts',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public Identifier')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Complete', 'Complete'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('reason', models.CharField(default='', max_length=50)),
                ('notes', models.TextField(default='')),
                ('transaction_type', models.CharField(max_length=15, null=True)),
                ('receiver_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='credit_transactions', to='wallets.account')),
                ('sender_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debit_transactions', to='wallets.account')),
            ],
            options={
                'db_table': 'wallet_transactions',
            },
        ),
    ]
