# Generated by Django 4.1.4 on 2023-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='available_account_balance',
            field=models.FloatField(null=True, verbose_name="Account's balance before the transaction"),
        ),
    ]
