# Generated by Django 4.1.4 on 2023-01-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_transaction_account_balance_after'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='created_at_desc_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 18)), name='balance_gte_0'),
        ),
    ]
